<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="TestCollector-20231031110144" tests="3" file=".py" time="0.007" timestamp="2023-10-31T11:01:47" failures="0" errors="3" skipped="0">
	<testcase classname="TestCollector" name="test_collect" time="0.006" timestamp="2023-10-31T11:01:47" file="test_cloudservice_api.py" line="53">
		<error type="AttributeError" message="'TestCollector' object has no attribute 'inventory'"><![CDATA[Traceback (most recent call last):
  File "C:\Users\e268\plugin-naver-cloud-service-inven-collector\test\api\test_cloudservice_api.py", line 75, in test_collect
    resource_stream = self.inventory.Collector.collect({
AttributeError: 'TestCollector' object has no attribute 'inventory'
]]></error>
	</testcase>
	<testcase classname="TestCollector" name="test_init" time="0.000" timestamp="2023-10-31T11:01:47" file="test_cloudservice_api.py" line="43">
		<error type="AttributeError" message="'TestCollector' object has no attribute 'inventory'"><![CDATA[Traceback (most recent call last):
  File "C:\Users\e268\plugin-naver-cloud-service-inven-collector\test\api\test_cloudservice_api.py", line 44, in test_init
    v_info = self.inventory.Collector.init({'options': {}})
AttributeError: 'TestCollector' object has no attribute 'inventory'
]]></error>
	</testcase>
	<testcase classname="TestCollector" name="test_verify" time="0.001" timestamp="2023-10-31T11:01:47" file="test_cloudservice_api.py" line="47">
		<error type="AttributeError" message="'TestCollector' object has no attribute 'inventory'"><![CDATA[Traceback (most recent call last):
  File "C:\Users\e268\plugin-naver-cloud-service-inven-collector\test\api\test_cloudservice_api.py", line 50, in test_verify
    v_info = self.inventory.Collector.verify({'options': options, 'secret_data': self.secret_data})
AttributeError: 'TestCollector' object has no attribute 'inventory'
]]></error>
	</testcase>
</testsuite>
